language: python

python:
    - "2.7"
    - "3.3"

install:
    - pip install -r requirements.txt

before_script:
    - git config --global user.name 'Travis CI'
    - git config --global user.email 'test@example.com'

script:
    - nosetests -v

notifications:
    email: false
